project:
  type: website

website:
  title: "first-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:sources

  sidebar:
    - id: sources
      title: "Sources"
      style: "floating"
      background: "#ffffff"
      collapse-level: 2
      contents:
        - source-1.qmd
        - source-2.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    editor: source



